name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v2

      - name: 2. setup nodejs...
        uses: actions/setup-node@v2

      - name: 3. install dependencies...
        run: |
          npm install

      - name: 4. build
        run: |
          npm run build
      - name: 5. deploy 'dist files'
        run: |
          copy .\README.md .\dist\README.md
          cd dist
          git init
          git config user.name "XueFLY"
          git config user.email "xuefeng@kcalb.wang"
          git add .
          git commit -am "Feat: Github Action Auto Build"
          git push --force --quiet https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} master:gh-pages
